version: "3"
services:
  gitpod-base:
    # ─────────────────────────────────────────────────────────────────
    # docker-compose -f build.docker-compose.yml build gitpod-base
    # ─────────────────────────────────────────────────────────────────
    image: fjolsvin/gitpod-base
    build:
      context: ./base
      dockerfile: Dockerfile
      args:
        - USER=gitpod
        - UID=33333
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  gitpod-python:
    # ─────────────────────────────────────────────────────────────────
    # docker-compose -f build.docker-compose.yml build gitpod-python
    # ─────────────────────────────────────────────────────────────────
    image: fjolsvin/gitpod-python
    build:
      context: ./python
      dockerfile: Dockerfile
      args:
        - USER=gitpod
        - PYTHON_VERSION=3.9.2
    depends_on:
      - gitpod-base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

