[[layers]]
  name = "colorscheme"
[[layers]]
  name = "tools"
[[layers]]
  name = "format"
  format_on_save = true
[[layers]]
  name = "ctrlspace"
[[layers]]
  name = "ui"
[[layers]]
  name = "git"
[[layers]]
  name = "github"
[[layers]]
  name = "sudo"
[[layers]]
  name = "fzf"
[[layers]]
  name = "foldsearch"
[[layers]]
  name = "gtags"
  gtagslabel = "ctags"
[[layers]]
  name = 'autocomplete'
  autocomplete_method = "coc"
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"
[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 20
[[layers]]
  name = "checkers"
  lint_on_save="true"
  show_cursor_error="false"
[[layers]]
  name = "core#statusline"
[[layers]]
  name = "lang#extra"
[[layers]]
  name = "lang#dockerfile"
[[layers]]
  name = "lang#sh"
[[layers]]
  name = "lang#vim"
[[layers]]
  name = "lang#markdown"
[[layers]]
  name = "lang#ruby"
[[layers]]
  name = "lang#toml"
[[layers]]
  name = 'lang#json'
[[layers]]
  name = 'lang#yaml'
[[layers]]
  name = "lsp"
  filetypes = [
    "sh"
  ]
[options]
  filesearching_tools = ['fd', 'fd -H']
  filemanager = "defx"
  sidebar_direction = 'left'
  default_indent = 2
  shiftwidth=2
  guifont = "Sauce Code Pro Nerd Font Complete Mono:h22"
  spacevim_max_column = 80
  max_column = 110
  colorcolumn = 120
  automatic_update = true
  filetree_direction = "left"
  enable_vimfiler_gitstatus = true
  rehash256 = 1
  autowite = 1
  autocomplete_method = "coc"
  updatetime=100
  rainbow_active = 1
  bootstrap_before = "init#before"
  bootstrap_after = "init#after"
