version: "3"
services:
  consul-replicate:
    # ─────────────────────────────────────────────────────────────────
    # docker-compose -f build.docker-compose.yml build consul-replicate
    # ─────────────────────────────────────────────────────────────────
    image: fjolsvin/consul-replicate
    build:
      context: ./
      dockerfile: consul-replicate.Dockerfile
      args:
        - USER=operator
  wrk:
    # ─────────────────────────────────────────────────────────────────
    # docker-compose -f build.docker-compose.yml build wrk
    # ─────────────────────────────────────────────────────────────────
    image: fjolsvin/wrk
    build:
      context: ./
      dockerfile: wrk.Dockerfile